from django.utils.translation import gettext_lazy as _

LANGUAGE_CHOICES = [
    ('', '---------'),
    ('deu', 'German'),
    ('eng', 'English'),
    ('tgl', 'Tagalog'),
    ('taw', 'Thai')
]


PRIVACY_LABEL = _('Datenschutzhinweis: Selbstverständlich werden Ihre Daten vertraulich behandelt und erst nach ' \
                  'Ihrer Zustimmung an Dritte weitergegeben. Ja, ich erkläre mich mit den Datenschutzbestimmungen ' \
                  'einverstanden.')

NATIONALITY_CHOICES_RAW = [
    "Afghan",
    "Egyptian",
    "Albanian",
    "Algerian",
    "United States",
    "Andorran",
    "Angolan",
    "Arabic",
    "Arabic (Saudi Arabia)",
    "Argentinian",
    "Armenian",
    "Azerbaijani",
    "Hong Kong",
    "Ethiopian",
    "Australian",
    "Bahamian",
    "Bahraini",
    "Bangladeshi",
    "Barbadian",
    "Belgian",
    "Belizean",
    "Beninese",
    "Bhutanese",
    "Bolivian",
    "Bosnian",
    "Botswanan",
    "Brazilian",
    "British",
    "British Virgin Islands",
    "Bruneian",
    "Bugarian",
    "Burkinabe",
    "Burundian",
    "Capetonian",
    "Cayman Islands",
    "Chad",
    "Chilean",
    "Chinese",
    "Costa Rican",
    "Danish",
    "German",
    "Djibouti",
    "Dominican",
    "Ecuadorian",
    "Eritrean",
    "Estonian",
    "Fijian",
    "Finnish",
    "French",
    "French (Guadeloupe)",
    "French Polynesia",
    "Gabon",
    "Gambian",
    "Georgian",
    "Ghanaian",
    "Greek",
    "Guam",
    "Guatemalan",
    "Guyana",
    "Haitian",
    "Honduran",
    "Indian",
    "Indonesian",
    "Iraqi",
    "Iranian",
    "Irish",
    "Icelandic",
    "Israeli",
    "Italian",
    "Ivorian",
    "Jamaican",
    "Japanese",
    "Yemeni",
    "Jersey",
    "Jordanian",
    "Caledonian",
    "Cambodian",
    "Cameroonian",
    "Canadian",
    "Kazakh",
    "Kenyan",
    "Kyrgyzstan",
    "Colombian",
    "Congolese",
    "Korean",
    "Croatian",
    "Cuban",
    "Kuwaiti",
    "Laotian",
    "Latvian",
    "Lebanese",
    "Liechtenstein",
    "Lithuanian",
    "Luxembourgian",
    "Macao",
    "Madagascan",
    "Malaysian",
    "Maldivian",
    "Malian",
    "Moroccan",
    "Mauretanian",
    "Mauritius",
    "Mexican",
    "Micronesian",
    "Moldovan",
    "Monacan",
    "Mongolian",
    "Mozambican",
    "Burmese",
    "Namibian",
    "Nepali",
    "New Zealand",
    "Nicaragua",
    "Dutch",
    "Dutch (Aruba)",
    "Dutch (Netherlands Antilles)",
    "Nigerian",
    "North Korean",
    "Nothern Mariana Islands",
    "Norwegian",
    "Omani",
    "Austrian",
    "Pakistani",
    "Palestine",
    "Palau",
    "Panamanian",
    "Papua New Guninea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Polish",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Rwandan",
    "Romanian",
    "Russian",
    "Zambian",
    "Swedish",
    "Swiss",
    "Senegal",
    "Serbian",
    "Zimbabwean",
    "Singaporean",
    "Slovak",
    "Slovenian",
    "Somali",
    "Spanish",
    "Sri-Lankan",
    "St. Vincent &amp; The Grenadines",
    "South African",
    "Sudanese",
    "Syrian",
    "Taiwanese",
    "Tanzanian",
    "Thai",
    "Togolese",
    "Trinidad &amp; Tobago",
    "Czech",
    "Tunisian",
    "Turkish",
    "Turkmenian",
    "Ugandan",
    "Ukrainian",
    "Hungarian",
    "Uruguayan",
    "Uzbekistan",
    "Venezuelan",
    "Vietnamese",
    "Virgin Islands (USA)",
    "Byelorussian",
    "West Indies",
    "Cypriot"
]

NATIONALITY_CHOICES = [('', '---------')] + list(map(lambda x: (x, x), NATIONALITY_CHOICES_RAW))
