# Generated by Django 4.0.3 on 2022-03-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=200)),
                ('your_email', models.CharField(max_length=200)),
                ('referral_name', models.CharField(max_length=200)),
                ('referral_email', models.CharField(max_length=200)),
                ('referral_phone', models.CharField(max_length=200)),
                ('referral_job', models.CharField(max_length=50)),
                ('referral_resume', models.FileField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
            },
        ),
    ]
