# Generated by Django 4.0.3 on 2022-03-21 11:31

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantWhyToWorkWithUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(max_length=100, verbose_name='Header > Title')),
                ('text_title', models.CharField(max_length=200, verbose_name='Text > Title')),
                ('text_sub', models.CharField(max_length=200, verbose_name='Text > Sub')),
                ('text_content', tinymce.models.HTMLField(verbose_name='Text > Content')),
                ('text_button', models.CharField(max_length=200, verbose_name='Text > Button')),
            ],
            options={
                'verbose_name': 'Page > Applicant Why To Work With Us',
            },
        ),
    ]
