# Generated by Django 4.0.3 on 2022-03-21 11:45

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantwhytoworkwithuspage',
            name='header_title_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Header > Title'),
        ),
        migrations.AddField(
            model_name='applicantwhytoworkwithuspage',
            name='header_title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Header > Title'),
        ),
        migrations.AddField(
            model_name='applicantwhytoworkwithuspage',
            name='text_button_de',
            field=models.CharField(max_length=200, null=True, verbose_name='Text > Button'),
        ),
        migrations.AddField(
            model_name='applicantwhytoworkwithuspage',
            name='text_button_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Text > Button'),
        ),
        migrations.AddField(
            model_name='applicantwhytoworkwithuspage',
            name='text_content_de',
            field=tinymce.models.HTMLField(null=True, verbose_name='Text > Content'),
        ),
        migrations.AddField(
            model_name='applicantwhytoworkwithuspage',
            name='text_content_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Text > Content'),
        ),
        migrations.AddField(
            model_name='applicantwhytoworkwithuspage',
            name='text_sub_de',
            field=models.CharField(max_length=200, null=True, verbose_name='Text > Sub'),
        ),
        migrations.AddField(
            model_name='applicantwhytoworkwithuspage',
            name='text_sub_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Text > Sub'),
        ),
        migrations.AddField(
            model_name='applicantwhytoworkwithuspage',
            name='text_title_de',
            field=models.CharField(max_length=200, null=True, verbose_name='Text > Title'),
        ),
        migrations.AddField(
            model_name='applicantwhytoworkwithuspage',
            name='text_title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Text > Title'),
        ),
    ]
