# Generated by Django 4.0.3 on 2022-04-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
