# Generated by Django 4.0.3 on 2022-04-07 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='content/member/image/')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MemberCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=models.ImageField(upload_to='content/applicant/photo/', verbose_name='Photo'),
        ),
        migrations.CreateModel(
            name='MemberCategoryConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.membercategory')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.member')),
            ],
        ),
        migrations.AddField(
            model_name='membercategory',
            name='members',
            field=models.ManyToManyField(through='content.MemberCategoryConnection', to='content.member'),
        ),
    ]
