# Generated by Django 4.0.3 on 2022-03-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_applicantwhytoworkwithuspage_header_title_de_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicantWhyToWorkWithUsPage',
            new_name='WhyToWorkWithUsPage',
        ),
    ]
