# Generated by Django 4.0.3 on 2022-03-21 12:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rename_applicantwhytoworkwithuspage_whytoworkwithuspage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whytoworkwithuspage',
            name='text_content',
        ),
        migrations.RemoveField(
            model_name='whytoworkwithuspage',
            name='text_content_de',
        ),
        migrations.RemoveField(
            model_name='whytoworkwithuspage',
            name='text_content_en',
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='text_left',
            field=tinymce.models.HTMLField(default='', verbose_name='Text > Left'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='text_left_de',
            field=tinymce.models.HTMLField(null=True, verbose_name='Text > Left'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='text_left_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Text > Left'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='text_right',
            field=tinymce.models.HTMLField(default='', verbose_name='Text > Right'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='text_right_de',
            field=tinymce.models.HTMLField(null=True, verbose_name='Text > Right'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='text_right_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Text > Right'),
        ),
    ]
