# Generated by Django 4.0.3 on 2022-03-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_whytoworkwithuspage_text_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('image_de', models.ImageField(null=True, upload_to='')),
                ('image_en', models.ImageField(null=True, upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('name_de', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100)),
                ('title_de', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('text', models.TextField()),
                ('text_de', models.TextField(null=True)),
                ('text_en', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
