# Generated by Django 4.0.3 on 2022-03-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image_de',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image_en',
        ),
    ]
