# Generated by Django 4.0.3 on 2022-04-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_membercategory_members_member_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='role_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='membercategory',
            name='title_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='membercategory',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
