# Generated by Django 4.0.3 on 2022-03-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_service_image_de_remove_service_image_en'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['ordering'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='service',
            name='ordering',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
