# Generated by Django 4.0.3 on 2022-04-07 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_member_role_de_member_role_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='membercategory',
            options={'verbose_name': 'Member Category', 'verbose_name_plural': 'Member Categories'},
        ),
        migrations.AlterField(
            model_name='member',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='content.membercategory'),
        ),
    ]
