# Generated by Django 4.0.3 on 2022-03-22 13:39

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_service_options_service_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitReferralPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(max_length=100, verbose_name='Header > Title')),
                ('text_title', models.CharField(max_length=200, verbose_name='Text > Title')),
                ('text_sub', models.CharField(max_length=200, verbose_name='Text > Sub')),
                ('text_left', tinymce.models.HTMLField(verbose_name='Text > Left')),
                ('text_right', tinymce.models.HTMLField(verbose_name='Text > Right')),
                ('text_button', models.CharField(max_length=200, verbose_name='Text > Button')),
                ('faq_title', models.CharField(max_length=100, verbose_name='FAQ > Title')),
                ('faq_question_1', models.CharField(blank=True, max_length=100, verbose_name='FAQ > Question 1')),
                ('faq_answer_1', models.TextField(blank=True, verbose_name='FAQ > Answer 1')),
                ('faq_question_2', models.CharField(blank=True, max_length=100, verbose_name='FAQ > Question 2')),
                ('faq_answer_2', models.TextField(blank=True, verbose_name='FAQ > Answer 2')),
                ('faq_question_3', models.CharField(blank=True, max_length=100, verbose_name='FAQ > Question 3')),
                ('faq_answer_3', models.TextField(blank=True, verbose_name='FAQ > Answer 3')),
                ('faq_question_4', models.CharField(blank=True, max_length=100, verbose_name='FAQ > Question 4')),
                ('faq_answer_4', models.TextField(blank=True, verbose_name='FAQ > Answer 4')),
                ('faq_question_5', models.CharField(blank=True, max_length=100, verbose_name='FAQ > Question 5')),
                ('faq_answer_5', models.TextField(blank=True, verbose_name='FAQ > Answer 5')),
                ('faq_question_6', models.CharField(blank=True, max_length=100, verbose_name='FAQ > Question 6')),
                ('faq_answer_6', models.TextField(blank=True, verbose_name='FAQ > Answer 6')),
            ],
            options={
                'verbose_name': 'Page > Submit A Referral Page',
            },
        ),
    ]
