# Generated by Django 4.0.3 on 2022-03-22 13:40

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_submitreferralpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitreferralpage',
            name='faq_answer_1_de',
            field=models.TextField(blank=True, null=True, verbose_name='FAQ > Answer 1'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='faq_answer_1_en',
            field=models.TextField(blank=True, null=True, verbose_name='FAQ > Answer 1'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='faq_answer_2_de',
            field=models.TextField(blank=True, null=True, verbose_name='FAQ > Answer 2'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='faq_answer_2_en',
            field=models.TextField(blank=True, null=True, verbose_name='FAQ > Answer 2'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='faq_answer_3_de',
            field=models.TextField(blank=True, null=True, verbose_name='FAQ > Answer 3'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='faq_answer_3_en',
            field=models.TextField(blank=True, null=True, verbose_name='FAQ > Answer 3'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='faq_answer_4_de',
            field=models.TextField(blank=True, null=True, verbose_name='FAQ > Answer 4'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='faq_answer_4_en',
            field=models.TextField(blank=True, null=True, verbose_name='FAQ > Answer 4'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='faq_answer_5_de',
            field=models.TextField(blank=True, null=True, verbose_name='FAQ > Answer 5'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='faq_answer_5_en',
            field=models.TextField(blank=True, null=True, verbose_name='FAQ > Answer 5'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='faq_answer_6_de',
            field=models.TextField(blank=True, null=True, verbose_name='FAQ > Answer 6'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='faq_answer_6_en',
            field=models.TextField(blank=True, null=True, verbose_name='FAQ > Answer 6'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='faq_question_1_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FAQ > Question 1'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='faq_question_1_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FAQ > Question 1'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='faq_question_2_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FAQ > Question 2'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='faq_question_2_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FAQ > Question 2'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='faq_question_3_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FAQ > Question 3'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='faq_question_3_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FAQ > Question 3'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='faq_question_4_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FAQ > Question 4'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='faq_question_4_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FAQ > Question 4'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='faq_question_5_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FAQ > Question 5'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='faq_question_5_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FAQ > Question 5'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='faq_question_6_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FAQ > Question 6'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='faq_question_6_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FAQ > Question 6'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='faq_title_de',
            field=models.CharField(max_length=100, null=True, verbose_name='FAQ > Title'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='faq_title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='FAQ > Title'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='header_title_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Header > Title'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='header_title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Header > Title'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='text_button_de',
            field=models.CharField(max_length=200, null=True, verbose_name='Text > Button'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='text_button_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Text > Button'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='text_left_de',
            field=tinymce.models.HTMLField(null=True, verbose_name='Text > Left'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='text_left_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Text > Left'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='text_right_de',
            field=tinymce.models.HTMLField(null=True, verbose_name='Text > Right'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='text_right_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Text > Right'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='text_sub_de',
            field=models.CharField(max_length=200, null=True, verbose_name='Text > Sub'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='text_sub_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Text > Sub'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='text_title_de',
            field=models.CharField(max_length=200, null=True, verbose_name='Text > Title'),
        ),
        migrations.AddField(
            model_name='submitreferralpage',
            name='text_title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Text > Title'),
        ),
    ]
