# Generated by Django 4.0.3 on 2022-04-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_portalpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalpage',
            name='header_title_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='header_title_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
    ]
