# Generated by Django 4.0.3 on 2022-03-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_staffcategory_service_created_service_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffcategory',
            old_name='icon',
            new_name='image',
        ),
        migrations.AddField(
            model_name='staffcategory',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
