# Generated by Django 4.0.3 on 2022-04-14 10:33

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_contactpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprintPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre', models.CharField(blank=True, max_length=1000, verbose_name='Pre')),
                ('title', models.CharField(blank=True, max_length=1000, verbose_name='Title')),
                ('text', tinymce.models.HTMLField(blank=True, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Page > Imprint',
            },
        ),
    ]
