# Generated by Django 4.0.3 on 2022-03-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_applicantshowitworkspage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantshowitworkspage',
            name='plan_button',
            field=models.CharField(default='', max_length=100, verbose_name='Plan > Button'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicantshowitworkspage',
            name='plan_button_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Plan > Button'),
        ),
        migrations.AddField(
            model_name='applicantshowitworkspage',
            name='plan_button_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Plan > Button'),
        ),
    ]
