# Generated by Django 4.0.3 on 2022-04-14 10:34

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_imprintpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='imprintpage',
            name='pre_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Pre'),
        ),
        migrations.AddField(
            model_name='imprintpage',
            name='pre_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Pre'),
        ),
        migrations.AddField(
            model_name='imprintpage',
            name='text_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='imprintpage',
            name='text_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='imprintpage',
            name='title_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='imprintpage',
            name='title_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Title'),
        ),
    ]
