# Generated by Django 4.0.3 on 2022-04-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_imprintpage_pre_de_imprintpage_pre_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='area_of_expertise',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
