# Generated by Django 4.0.3 on 2022-03-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_coursespage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoursesPage',
            new_name='ServicesPage',
        ),
    ]
