# Generated by Django 4.0.3 on 2022-04-14 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_alter_applicant_language1knowledge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='looking_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.staffcategory'),
        ),
    ]
