# Generated by Django 4.0.3 on 2022-04-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_alter_company_looking_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='job_duration',
            field=models.CharField(choices=[('4', '4 Months'), ('6', '6 Months'), ('8', '8 Months'), ('12', '12 Months'), ('PERMANENT', 'Permanent')], max_length=100),
        ),
    ]
