# Generated by Django 4.0.3 on 2022-04-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_alter_company_job_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantshowitworkspage',
            name='quote_author',
            field=models.CharField(blank=True, max_length=200, verbose_name='Quote > Author'),
        ),
        migrations.AddField(
            model_name='applicantshowitworkspage',
            name='quote_author_de',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Quote > Author'),
        ),
        migrations.AddField(
            model_name='applicantshowitworkspage',
            name='quote_author_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Quote > Author'),
        ),
        migrations.AddField(
            model_name='applicantshowitworkspage',
            name='quote_quote',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Quote > Quote'),
        ),
        migrations.AddField(
            model_name='applicantshowitworkspage',
            name='quote_quote_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Quote > Quote'),
        ),
        migrations.AddField(
            model_name='applicantshowitworkspage',
            name='quote_quote_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Quote > Quote'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='quote_author',
            field=models.CharField(blank=True, max_length=200, verbose_name='Quote > Author'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='quote_author_de',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Quote > Author'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='quote_author_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Quote > Author'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='quote_quote',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Quote > Quote'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='quote_quote_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Quote > Quote'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='quote_quote_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Quote > Quote'),
        ),
    ]
