# Generated by Django 4.0.3 on 2022-03-26 11:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_employerfaqpage_faq_answer_1_de_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffingSolutionsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(blank=True, max_length=1000, verbose_name='Header > Title')),
                ('header_title_de', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Header > Title')),
                ('header_title_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Header > Title')),
                ('text_title', models.CharField(blank=True, max_length=1000, verbose_name='Text > Title')),
                ('text_title_de', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Text > Title')),
                ('text_title_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Text > Title')),
                ('text_sub', models.CharField(blank=True, max_length=1000, verbose_name='Text > Sub')),
                ('text_sub_de', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Text > Sub')),
                ('text_sub_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Text > Sub')),
                ('text_text', tinymce.models.HTMLField(blank=True, verbose_name='Text > Text')),
                ('text_text_de', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text > Text')),
                ('text_text_en', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text > Text')),
                ('solutions_title', models.CharField(blank=True, max_length=1000, verbose_name='Solutions > Title')),
                ('solutions_title_de', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Solutions > Title')),
                ('solutions_title_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Solutions > Title')),
                ('cta_title', models.CharField(blank=True, max_length=1000, verbose_name='Cta > Sub')),
                ('cta_title_de', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Cta > Sub')),
                ('cta_title_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Cta > Sub')),
                ('cta_text', models.TextField(blank=True, verbose_name='Cta > Text')),
                ('cta_text_de', models.TextField(blank=True, null=True, verbose_name='Cta > Text')),
                ('cta_text_en', models.TextField(blank=True, null=True, verbose_name='Cta > Text')),
                ('cta_button', models.CharField(blank=True, max_length=1000, verbose_name='Cta > Button')),
                ('cta_button_de', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Cta > Button')),
                ('cta_button_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Cta > Button')),
            ],
            options={
                'verbose_name': 'Page > Staffing Solutions',
            },
        ),
    ]
