# Generated by Django 4.0.3 on 2022-04-22 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_remove_applicant_area_of_expertise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='content.staffcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='experience',
            field=models.CharField(choices=[('1', '1 Year'), ('5', '1 to 5 Years'), ('10', '5 to 10 Years'), ('MAX', 'More Than 10 Years')], default=None, max_length=100),
            preserve_default=False,
        ),
    ]
