# Generated by Django 4.0.3 on 2022-03-26 11:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_alter_staffingsolutionspage_cta_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whytoworkwithuspage',
            name='text_left',
        ),
        migrations.RemoveField(
            model_name='whytoworkwithuspage',
            name='text_left_de',
        ),
        migrations.RemoveField(
            model_name='whytoworkwithuspage',
            name='text_left_en',
        ),
        migrations.RemoveField(
            model_name='whytoworkwithuspage',
            name='text_right',
        ),
        migrations.RemoveField(
            model_name='whytoworkwithuspage',
            name='text_right_de',
        ),
        migrations.RemoveField(
            model_name='whytoworkwithuspage',
            name='text_right_en',
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='text_text',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Text > Text'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='text_text_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text > Text'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='text_text_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text > Text'),
        ),
    ]
