# Generated by Django 4.0.3 on 2022-03-26 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_remove_whytoworkwithuspage_text_left_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitreferralpage',
            name='text_left',
        ),
        migrations.RemoveField(
            model_name='submitreferralpage',
            name='text_left_de',
        ),
        migrations.RemoveField(
            model_name='submitreferralpage',
            name='text_left_en',
        ),
    ]
