# Generated by Django 4.0.3 on 2022-03-26 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_remove_submitreferralpage_text_left_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submitreferralpage',
            old_name='text_right',
            new_name='text_text',
        ),
        migrations.RenameField(
            model_name='submitreferralpage',
            old_name='text_right_de',
            new_name='text_text_de',
        ),
        migrations.RenameField(
            model_name='submitreferralpage',
            old_name='text_right_en',
            new_name='text_text_en',
        ),
    ]
