# Generated by Django 4.0.3 on 2022-03-26 11:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_rename_text_right_submitreferralpage_text_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitreferralpage',
            name='text_text',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Text > Text'),
        ),
        migrations.AlterField(
            model_name='submitreferralpage',
            name='text_text_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text > Text'),
        ),
        migrations.AlterField(
            model_name='submitreferralpage',
            name='text_text_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text > Text'),
        ),
    ]
