# Generated by Django 4.0.3 on 2022-04-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='employer_how_it_works',
            field=models.CharField(blank=True, max_length=200, verbose_name='Employer > How It Works'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='employer_how_it_works_de',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Employer > How It Works'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='employer_how_it_works_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Employer > How It Works'),
        ),
    ]
