# Generated by Django 4.0.3 on 2022-03-26 12:12

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_alter_submitreferralpage_text_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitPositionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(blank=True, max_length=1000, verbose_name='Header > Title')),
                ('header_title_de', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Header > Title')),
                ('header_title_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Header > Title')),
                ('form_title', models.CharField(blank=True, max_length=1000, verbose_name='Form > Title')),
                ('form_title_de', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Form > Title')),
                ('form_title_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Form > Title')),
                ('form_text', tinymce.models.HTMLField(blank=True, verbose_name='Form > Text')),
                ('form_text_de', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Form > Text')),
                ('form_text_en', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Form > Text')),
            ],
            options={
                'verbose_name': 'Page > Submit A Position',
            },
        ),
    ]
