# Generated by Django 4.0.3 on 2022-03-26 12:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_submitpositionpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='header_title_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='header_title_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='text_sub_de',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Text > Sub'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='text_sub_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Text > Sub'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='text_text_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text > Text'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='text_text_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text > Text'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='text_title_de',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Text > Title'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='text_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Text > Title'),
        ),
    ]
