# Generated by Django 4.0.3 on 2022-04-25 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_alter_applicant_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='birthday',
            field=models.DateField(verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='cv',
            field=models.FileField(upload_to='applicants/applicant/cv/', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='content.staffcategory', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='employer',
            field=models.CharField(max_length=50, verbose_name='Employer'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='experience',
            field=models.CharField(choices=[('1', '1 Year'), ('5', '1 to 5 Years'), ('10', '5 to 10 Years'), ('MAX', 'More Than 10 Years')], max_length=100, verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='from_date',
            field=models.DateField(verbose_name='From Date'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='Lastname'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='marital_status',
            field=models.CharField(choices=[('SINGLE', 'Ledig'), ('DIVORCED', 'Geschieden'), ('SEPERATED', 'Getrennt lebend'), ('MARRIED', 'Verheiratet'), ('WIDOWED', 'Verwitwet')], max_length=20, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='more',
            field=models.FileField(blank=True, upload_to='applicants/applicant/more/', verbose_name='More'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='nationality',
            field=models.CharField(max_length=100, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='position',
            field=models.CharField(max_length=50, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='postal',
            field=models.CharField(max_length=10, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='until_date',
            field=models.DateField(verbose_name='Until Date'),
        ),
    ]
