# Generated by Django 4.0.3 on 2022-05-03 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_alter_applicant_birthday_alter_applicant_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='show',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.EmailField(max_length=254, verbose_name='Company E-Mail'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_phone',
            field=models.CharField(max_length=30, verbose_name='Company Phone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='job_description',
            field=models.TextField(verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='job_duration',
            field=models.CharField(choices=[('4', '4 Months'), ('6', '6 Months'), ('8', '8 Months'), ('12', '12 Months'), ('PERMANENT', 'Permanent')], max_length=100, verbose_name='Job Duration'),
        ),
        migrations.AlterField(
            model_name='company',
            name='job_position',
            field=models.CharField(max_length=200, verbose_name='Job Position'),
        ),
        migrations.AlterField(
            model_name='company',
            name='job_start',
            field=models.DateField(verbose_name='Job Start'),
        ),
        migrations.AlterField(
            model_name='company',
            name='looking_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.staffcategory', verbose_name='Looking for'),
        ),
        migrations.AlterField(
            model_name='company',
            name='manager_name',
            field=models.CharField(max_length=200, verbose_name='Manager Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='role_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='role_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_email',
            field=models.CharField(max_length=200, verbose_name='Referral E-Mail'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_job',
            field=models.CharField(max_length=50, verbose_name='Referral Job'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_name',
            field=models.CharField(max_length=200, verbose_name='Referral Name'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_phone',
            field=models.CharField(max_length=200, verbose_name='Referral Phone'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_resume',
            field=models.FileField(upload_to='', verbose_name='Referral Resume'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='your_email',
            field=models.CharField(max_length=200, verbose_name='Your E-Mail'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='your_name',
            field=models.CharField(max_length=200, verbose_name='Your Name'),
        ),
    ]
