# Generated by Django 4.0.3 on 2022-04-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_alter_service_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitReferralThanksPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Page > Submit A Referral Thanks',
            },
        ),
    ]
