# Generated by Django 4.0.3 on 2022-04-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_submitreferralthankspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativeApplicationThanksPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Page > Initiative Application Thanks',
            },
        ),
        migrations.CreateModel(
            name='SubmitPositionThanksPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Page > Submit A Position Thanks',
            },
        ),
    ]
