# Generated by Django 4.0.3 on 2022-05-04 16:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_videoresumepage_quote_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerfaqpage',
            name='faq_answer_1',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 1'),
        ),
        migrations.AlterField(
            model_name='jobseekerfaqpage',
            name='faq_answer_1_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 1'),
        ),
        migrations.AlterField(
            model_name='jobseekerfaqpage',
            name='faq_answer_1_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 1'),
        ),
    ]
