# Generated by Django 4.0.3 on 2022-05-04 16:58

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_jobseekerfaqpage_faq_answer_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_1',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 1'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_10',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 10'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_10_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 10'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_10_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 10'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_11',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 11'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_11_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 11'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_11_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 11'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_12',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 12'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_12_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 12'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_12_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 12'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_13',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 13'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_13_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 13'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_13_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 13'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_14',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 14'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_14_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 14'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_14_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 14'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_15',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 15'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_15_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 15'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_15_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 15'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_16',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 16'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_16_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 16'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_16_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 16'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_17',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 17'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_17_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 17'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_17_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 17'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_18',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 18'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_18_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 18'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_18_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 18'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_19',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 19'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_19_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 19'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_19_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 19'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_1_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 1'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_1_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 1'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_2',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 2'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_20',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 20'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_20_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 20'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_20_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 20'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_2_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 2'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_2_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 2'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_3',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 3'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_3_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 3'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_3_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 3'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_4',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 4'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_4_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 4'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_4_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 4'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_5',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 5'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_5_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 5'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_5_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 5'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_6',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 6'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_6_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 6'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_6_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 6'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_7',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 7'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_7_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 7'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_7_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 7'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_8',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 8'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_8_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 8'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_8_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 8'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_9',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 9'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_9_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 9'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_answer_9_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 9'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_1',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 1'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_10',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 10'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_10_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 10'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_10_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 10'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_11',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 11'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_11_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 11'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_11_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 11'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_12',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 12'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_12_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 12'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_12_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 12'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_13',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 13'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_13_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 13'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_13_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 13'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_14',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 14'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_14_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 14'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_14_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 14'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_15',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 15'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_15_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 15'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_15_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 15'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_16',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 16'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_16_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 16'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_16_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 16'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_17',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 17'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_17_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 17'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_17_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 17'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_18',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 18'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_18_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 18'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_18_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 18'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_19',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 19'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_19_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 19'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_19_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 19'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_1_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 1'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_1_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 1'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_2',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 2'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_20',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 20'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_20_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 20'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_20_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 20'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_2_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 2'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_2_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 2'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_3',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 3'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_3_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 3'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_3_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 3'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_4',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 4'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_4_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 4'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_4_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 4'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_5',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 5'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_5_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 5'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_5_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 5'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_6',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 6'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_6_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 6'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_6_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 6'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_7',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 7'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_7_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 7'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_7_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 7'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_8',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 8'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_8_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 8'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_8_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 8'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_9',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 9'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_9_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 9'),
        ),
        migrations.AddField(
            model_name='workinginaustriapage',
            name='faq_question_9_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 9'),
        ),
    ]
