# Generated by Django 4.0.3 on 2022-05-04 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_workinginaustriapage_faq_answer_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='job_seeker_service_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_1', to='content.service', verbose_name='Job Seeker > Service 1'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='job_seeker_service_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_2', to='content.service', verbose_name='Job Seeker > Service 2'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='job_seeker_service_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_3', to='content.service', verbose_name='Job Seeker > Service 3'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='job_seeker_service_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_4', to='content.service', verbose_name='Job Seeker > Service 4'),
        ),
    ]
