# Generated by Django 4.0.3 on 2022-05-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_navigation_job_seeker_service_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='accommodation',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
