# Generated by Django 4.0.3 on 2022-05-13 09:37

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0044_remove_servicespage_quote_quote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgbPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre', models.CharField(blank=True, max_length=1000, verbose_name='Pre')),
                ('pre_de', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Pre')),
                ('pre_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Pre')),
                ('title', models.CharField(blank=True, max_length=1000, verbose_name='Title')),
                ('title_de', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Title')),
                ('text', tinymce.models.HTMLField(blank=True, verbose_name='Text')),
                ('text_de', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text')),
                ('text_en', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Page > Agb',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre', models.CharField(blank=True, max_length=1000, verbose_name='Pre')),
                ('pre_de', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Pre')),
                ('pre_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Pre')),
                ('title', models.CharField(blank=True, max_length=1000, verbose_name='Title')),
                ('title_de', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Title')),
                ('text', tinymce.models.HTMLField(blank=True, verbose_name='Text')),
                ('text_de', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text')),
                ('text_en', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Page > Privacy',
            },
        ),
    ]
