# Generated by Django 4.0.3 on 2022-05-13 10:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0045_agbpage_privacypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_1',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 1'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_10',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 10'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_10_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 10'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_10_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 10'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_1_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 1'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_1_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 1'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_2',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 2'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_2_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 2'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_2_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 2'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_3',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 3'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_3_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 3'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_3_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 3'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_4',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 4'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_4_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 4'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_4_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 4'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_5',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 5'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_5_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 5'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_5_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 5'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_6',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 6'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_6_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 6'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_6_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 6'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_7',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 7'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_7_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 7'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_7_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 7'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_8',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 8'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_8_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 8'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_8_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 8'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_9',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 9'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_9_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 9'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_answer_9_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 9'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_1',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 1'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_10',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 10'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_10_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 10'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_10_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 10'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_1_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 1'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_1_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 1'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_2',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 2'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_2_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 2'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_2_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 2'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_3',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 3'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_3_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 3'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_3_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 3'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_4',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 4'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_4_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 4'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_4_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 4'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_5',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 5'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_5_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 5'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_5_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 5'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_6',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 6'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_6_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 6'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_6_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 6'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_7',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 7'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_7_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 7'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_7_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 7'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_8',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 8'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_8_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 8'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_8_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 8'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_9',
            field=models.CharField(blank=True, max_length=1000, verbose_name='FAQ > Question 9'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_9_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 9'),
        ),
        migrations.AddField(
            model_name='whytoworkwithuspage',
            name='faq_question_9_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FAQ > Question 9'),
        ),
    ]
