# Generated by Django 4.0.3 on 2022-05-13 10:24

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0046_whytoworkwithuspage_faq_answer_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerHowItWorksPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(blank=True, max_length=1000, verbose_name='Header > Title')),
                ('header_title_de', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Header > Title')),
                ('header_title_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Header > Title')),
                ('text_title', models.CharField(blank=True, max_length=200, verbose_name='Text > Title')),
                ('text_title_de', models.CharField(blank=True, max_length=200, null=True, verbose_name='Text > Title')),
                ('text_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Text > Title')),
                ('text_sub', models.CharField(blank=True, max_length=200, verbose_name='Text > Sub')),
                ('text_sub_de', models.CharField(blank=True, max_length=200, null=True, verbose_name='Text > Sub')),
                ('text_sub_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Text > Sub')),
                ('text_text', tinymce.models.HTMLField(blank=True, verbose_name='Text > Text')),
                ('text_text_de', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text > Text')),
                ('text_text_en', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text > Text')),
                ('text_button', models.CharField(blank=True, max_length=200, verbose_name='Text > Button')),
                ('text_button_de', models.CharField(blank=True, max_length=200, null=True, verbose_name='Text > Button')),
                ('text_button_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Text > Button')),
                ('plan_title', models.CharField(blank=True, max_length=1000, verbose_name='Plan > Title')),
                ('plan_title_de', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Plan > Title')),
                ('plan_title_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Plan > Title')),
                ('plan_1', models.TextField(blank=True, verbose_name='Plan > Step 1')),
                ('plan_1_de', models.TextField(blank=True, null=True, verbose_name='Plan > Step 1')),
                ('plan_1_en', models.TextField(blank=True, null=True, verbose_name='Plan > Step 1')),
                ('plan_2', models.TextField(blank=True, verbose_name='Plan > Step 2')),
                ('plan_2_de', models.TextField(blank=True, null=True, verbose_name='Plan > Step 2')),
                ('plan_2_en', models.TextField(blank=True, null=True, verbose_name='Plan > Step 2')),
                ('plan_3', models.TextField(blank=True, verbose_name='Plan > Step 3')),
                ('plan_3_de', models.TextField(blank=True, null=True, verbose_name='Plan > Step 3')),
                ('plan_3_en', models.TextField(blank=True, null=True, verbose_name='Plan > Step 3')),
                ('plan_4', models.TextField(blank=True, verbose_name='Plan > Step 4')),
                ('plan_4_de', models.TextField(blank=True, null=True, verbose_name='Plan > Step 4')),
                ('plan_4_en', models.TextField(blank=True, null=True, verbose_name='Plan > Step 4')),
                ('plan_5', models.TextField(blank=True, verbose_name='Plan > Step 5')),
                ('plan_5_de', models.TextField(blank=True, null=True, verbose_name='Plan > Step 5')),
                ('plan_5_en', models.TextField(blank=True, null=True, verbose_name='Plan > Step 5')),
                ('plan_button', models.CharField(blank=True, max_length=1000, verbose_name='Plan > Button')),
                ('plan_button_de', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Plan > Button')),
                ('plan_button_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Plan > Button')),
                ('quote_text', models.TextField(blank=True, verbose_name='Quote > Text')),
                ('quote_text_de', models.TextField(blank=True, null=True, verbose_name='Quote > Text')),
                ('quote_text_en', models.TextField(blank=True, null=True, verbose_name='Quote > Text')),
                ('quote_author', models.CharField(blank=True, max_length=200, verbose_name='Quote > Author')),
                ('quote_author_de', models.CharField(blank=True, max_length=200, null=True, verbose_name='Quote > Author')),
                ('quote_author_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Quote > Author')),
            ],
            options={
                'verbose_name': 'Page > Employer How It Works',
            },
        ),
    ]
