# Generated by Django 4.0.3 on 2022-05-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_submitpositionpage_email_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Company Phone'),
        ),
    ]
