# Generated by Django 4.0.3 on 2022-05-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0049_alter_company_company_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='language1knowledge',
            field=models.CharField(choices=[('MOTHER', 'Mother tongue'), ('FLUENT', 'Fluent in spoken and written'), ('GOOD', 'Good knowledge written and spoken'), ('BASIC', 'Basic knowledge')], max_length=50, verbose_name='Knowledge'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='language2knowledge',
            field=models.CharField(blank=True, choices=[('MOTHER', 'Mother tongue'), ('FLUENT', 'Fluent in spoken and written'), ('GOOD', 'Good knowledge written and spoken'), ('BASIC', 'Basic knowledge')], max_length=50, verbose_name='Knowledge'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='language3knowledge',
            field=models.CharField(blank=True, choices=[('MOTHER', 'Mother tongue'), ('FLUENT', 'Fluent in spoken and written'), ('GOOD', 'Good knowledge written and spoken'), ('BASIC', 'Basic knowledge')], max_length=50, verbose_name='Knowledge'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='language4knowledge',
            field=models.CharField(blank=True, choices=[('MOTHER', 'Mother tongue'), ('FLUENT', 'Fluent in spoken and written'), ('GOOD', 'Good knowledge written and spoken'), ('BASIC', 'Basic knowledge')], max_length=50, verbose_name='Knowledge'),
        ),
    ]
