# Generated by Django 4.0.3 on 2022-05-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0050_alter_applicant_language1knowledge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='accommodation',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, verbose_name='Accomodation provided'),
        ),
    ]
