# Generated by Django 4.0.3 on 2022-05-17 08:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0051_alter_company_accommodation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerfaqpage',
            name='faq_answer_1',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 1'),
        ),
        migrations.AlterField(
            model_name='employerfaqpage',
            name='faq_answer_1_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 1'),
        ),
        migrations.AlterField(
            model_name='employerfaqpage',
            name='faq_answer_1_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 1'),
        ),
        migrations.AlterField(
            model_name='employerfaqpage',
            name='faq_answer_2',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 2'),
        ),
        migrations.AlterField(
            model_name='employerfaqpage',
            name='faq_answer_2_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 2'),
        ),
        migrations.AlterField(
            model_name='employerfaqpage',
            name='faq_answer_2_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 2'),
        ),
        migrations.AlterField(
            model_name='employerfaqpage',
            name='faq_answer_3',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 3'),
        ),
        migrations.AlterField(
            model_name='employerfaqpage',
            name='faq_answer_3_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 3'),
        ),
        migrations.AlterField(
            model_name='employerfaqpage',
            name='faq_answer_3_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 3'),
        ),
        migrations.AlterField(
            model_name='employerfaqpage',
            name='faq_answer_4',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 4'),
        ),
        migrations.AlterField(
            model_name='employerfaqpage',
            name='faq_answer_4_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 4'),
        ),
        migrations.AlterField(
            model_name='employerfaqpage',
            name='faq_answer_4_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 4'),
        ),
        migrations.AlterField(
            model_name='employerfaqpage',
            name='faq_answer_5',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 5'),
        ),
        migrations.AlterField(
            model_name='employerfaqpage',
            name='faq_answer_5_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 5'),
        ),
        migrations.AlterField(
            model_name='employerfaqpage',
            name='faq_answer_5_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 5'),
        ),
        migrations.AlterField(
            model_name='employerfaqpage',
            name='faq_answer_6',
            field=tinymce.models.HTMLField(blank=True, verbose_name='FAQ > Answer 6'),
        ),
        migrations.AlterField(
            model_name='employerfaqpage',
            name='faq_answer_6_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 6'),
        ),
        migrations.AlterField(
            model_name='employerfaqpage',
            name='faq_answer_6_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='FAQ > Answer 6'),
        ),
    ]
