# Generated by Django 4.0.3 on 2022-05-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_alter_employerfaqpage_faq_answer_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='text_title',
            field=models.TextField(blank=True, max_length=200, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='text_title_de',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='text_title_en',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='applicantshowitworkspage',
            name='text_title',
            field=models.TextField(blank=True, max_length=200, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='applicantshowitworkspage',
            name='text_title_de',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='applicantshowitworkspage',
            name='text_title_en',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='employerfaqpage',
            name='text_title',
            field=models.TextField(blank=True, max_length=200, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='employerfaqpage',
            name='text_title_de',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='employerfaqpage',
            name='text_title_en',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='employerhowitworkspage',
            name='text_title',
            field=models.TextField(blank=True, max_length=200, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='employerhowitworkspage',
            name='text_title_de',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='employerhowitworkspage',
            name='text_title_en',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='text_title',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='text_title_de',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='text_title_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='jobseekerfaqpage',
            name='text_title',
            field=models.TextField(blank=True, max_length=200, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='jobseekerfaqpage',
            name='text_title_de',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='jobseekerfaqpage',
            name='text_title_en',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='text_title',
            field=models.TextField(blank=True, max_length=200, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='text_title_de',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='text_title_en',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='staffingsolutionspage',
            name='text_title',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='staffingsolutionspage',
            name='text_title_de',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='staffingsolutionspage',
            name='text_title_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='submitreferralpage',
            name='text_title',
            field=models.TextField(blank=True, max_length=200, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='submitreferralpage',
            name='text_title_de',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='submitreferralpage',
            name='text_title_en',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='videoresumepage',
            name='text_title',
            field=models.TextField(blank=True, max_length=200, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='videoresumepage',
            name='text_title_de',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='videoresumepage',
            name='text_title_en',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='whytoworkwithuspage',
            name='text_title',
            field=models.TextField(blank=True, max_length=200, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='whytoworkwithuspage',
            name='text_title_de',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='whytoworkwithuspage',
            name='text_title_en',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='workinginaustriapage',
            name='text_title',
            field=models.TextField(blank=True, max_length=200, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='workinginaustriapage',
            name='text_title_de',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Text > Title'),
        ),
        migrations.AlterField(
            model_name='workinginaustriapage',
            name='text_title_en',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Text > Title'),
        ),
    ]
