# Generated by Django 4.0.3 on 2022-05-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0053_alter_aboutpage_text_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='header_title',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='header_title_de',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='header_title_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='applicantshowitworkspage',
            name='header_title',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='applicantshowitworkspage',
            name='header_title_de',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='applicantshowitworkspage',
            name='header_title_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='header_title',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='header_title_de',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='header_title_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='employerfaqpage',
            name='header_title',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='employerfaqpage',
            name='header_title_de',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='employerfaqpage',
            name='header_title_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='employerhowitworkspage',
            name='header_title',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='employerhowitworkspage',
            name='header_title_de',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='employerhowitworkspage',
            name='header_title_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='header_title',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='header_title_de',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='header_title_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='initiativeapplicationpage',
            name='header_title',
            field=models.TextField(blank=True, max_length=200, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='initiativeapplicationpage',
            name='header_title_de',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='initiativeapplicationpage',
            name='header_title_en',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='jobseekerfaqpage',
            name='header_title',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='jobseekerfaqpage',
            name='header_title_de',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='jobseekerfaqpage',
            name='header_title_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='portalpage',
            name='header_title',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='portalpage',
            name='header_title_de',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='portalpage',
            name='header_title_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='header_title',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='header_title_de',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='header_title_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='staffingsolutionspage',
            name='header_title',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='staffingsolutionspage',
            name='header_title_de',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='staffingsolutionspage',
            name='header_title_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='submitpositionpage',
            name='header_title',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='submitpositionpage',
            name='header_title_de',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='submitpositionpage',
            name='header_title_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='submitreferralpage',
            name='header_title',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='submitreferralpage',
            name='header_title_de',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='submitreferralpage',
            name='header_title_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='videoresumepage',
            name='header_title',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='videoresumepage',
            name='header_title_de',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='videoresumepage',
            name='header_title_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='whytoworkwithuspage',
            name='header_title',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='whytoworkwithuspage',
            name='header_title_de',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='whytoworkwithuspage',
            name='header_title_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='workinginaustriapage',
            name='header_title',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='workinginaustriapage',
            name='header_title_de',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
        migrations.AlterField(
            model_name='workinginaustriapage',
            name='header_title_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header > Title'),
        ),
    ]
