# Generated by Django 4.0.3 on 2022-05-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0055_employerfaqpage_text_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeapplicationpage',
            name='header_text',
            field=models.TextField(blank=True, verbose_name='Header > Text'),
        ),
        migrations.AddField(
            model_name='initiativeapplicationpage',
            name='header_text_de',
            field=models.TextField(blank=True, null=True, verbose_name='Header > Text'),
        ),
        migrations.AddField(
            model_name='initiativeapplicationpage',
            name='header_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Header > Text'),
        ),
    ]
