# Generated by Django 4.0.3 on 2022-05-17 22:49

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0056_initiativeapplicationpage_header_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeapplicationpage',
            name='email_html',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Mail > Rich Text'),
        ),
        migrations.AddField(
            model_name='initiativeapplicationpage',
            name='email_html_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Mail > Rich Text'),
        ),
        migrations.AddField(
            model_name='initiativeapplicationpage',
            name='email_html_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Mail > Rich Text'),
        ),
        migrations.AddField(
            model_name='initiativeapplicationpage',
            name='email_subject',
            field=models.CharField(blank=True, max_length=300, verbose_name='Mail > Subject'),
        ),
        migrations.AddField(
            model_name='initiativeapplicationpage',
            name='email_subject_de',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Mail > Subject'),
        ),
        migrations.AddField(
            model_name='initiativeapplicationpage',
            name='email_subject_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Mail > Subject'),
        ),
        migrations.AddField(
            model_name='initiativeapplicationpage',
            name='email_text',
            field=models.TextField(blank=True, verbose_name='Mail > Text'),
        ),
        migrations.AddField(
            model_name='initiativeapplicationpage',
            name='email_text_de',
            field=models.TextField(blank=True, null=True, verbose_name='Mail > Text'),
        ),
        migrations.AddField(
            model_name='initiativeapplicationpage',
            name='email_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Mail > Text'),
        ),
    ]
