# Generated by Django 4.0.3 on 2022-05-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0058_remove_applicant_city_remove_applicant_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoresumepage',
            name='benefits_center_text',
            field=models.TextField(blank=True, verbose_name='Benefits > Text Center'),
        ),
        migrations.AddField(
            model_name='videoresumepage',
            name='benefits_center_text_de',
            field=models.TextField(blank=True, null=True, verbose_name='Benefits > Text Center'),
        ),
        migrations.AddField(
            model_name='videoresumepage',
            name='benefits_center_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Benefits > Text Center'),
        ),
        migrations.AddField(
            model_name='videoresumepage',
            name='benefits_center_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Benefits > Title Center'),
        ),
        migrations.AddField(
            model_name='videoresumepage',
            name='benefits_center_title_de',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Benefits > Title Center'),
        ),
        migrations.AddField(
            model_name='videoresumepage',
            name='benefits_center_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Benefits > Title Center'),
        ),
    ]
