# Generated by Django 4.0.3 on 2022-05-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0063_alter_staffingsolutionspage_solutions_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_1_text', models.TextField(blank=True, verbose_name='Column 1 > Text')),
                ('column_1_phone', models.CharField(blank=True, max_length=1000, verbose_name='Column 1 > Phone')),
                ('column_1_mail', models.CharField(blank=True, max_length=1000, verbose_name='Column 1 > Mail')),
                ('column_2_title', models.CharField(blank=True, max_length=1000, verbose_name='Column 2 > Title')),
                ('column_2_text_1', models.CharField(blank=True, max_length=1000, verbose_name='Column 2 > Text 1')),
                ('column_2_text_2', models.CharField(blank=True, max_length=1000, verbose_name='Column 2 > Text 2')),
                ('column_2_text_3', models.CharField(blank=True, max_length=1000, verbose_name='Column 2 > Text 3')),
                ('column_3_title', models.CharField(blank=True, max_length=1000, verbose_name='Column 3 > Title')),
                ('column_3_text_1', models.CharField(blank=True, max_length=1000, verbose_name='Column 3 > Text 1')),
                ('column_3_text_2', models.CharField(blank=True, max_length=1000, verbose_name='Column 3 > Text 2')),
                ('column_3_text_3', models.CharField(blank=True, max_length=1000, verbose_name='Column 3 > Text 3')),
                ('column_4_title', models.CharField(blank=True, max_length=1000, verbose_name='Column 4 > Title')),
                ('column_4_text_1', models.CharField(blank=True, max_length=1000, verbose_name='Column 4 > Text 1')),
            ],
            options={
                'verbose_name': 'Footer',
            },
        ),
    ]
