# Generated by Django 4.0.3 on 2022-05-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0064_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='column_1_mail_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Column 1 > Mail'),
        ),
        migrations.AddField(
            model_name='footer',
            name='column_1_mail_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Column 1 > Mail'),
        ),
        migrations.AddField(
            model_name='footer',
            name='column_1_phone_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Column 1 > Phone'),
        ),
        migrations.AddField(
            model_name='footer',
            name='column_1_phone_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Column 1 > Phone'),
        ),
        migrations.AddField(
            model_name='footer',
            name='column_1_text_de',
            field=models.TextField(blank=True, null=True, verbose_name='Column 1 > Text'),
        ),
        migrations.AddField(
            model_name='footer',
            name='column_1_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Column 1 > Text'),
        ),
        migrations.AddField(
            model_name='footer',
            name='column_2_text_1_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Column 2 > Text 1'),
        ),
        migrations.AddField(
            model_name='footer',
            name='column_2_text_1_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Column 2 > Text 1'),
        ),
        migrations.AddField(
            model_name='footer',
            name='column_2_text_2_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Column 2 > Text 2'),
        ),
        migrations.AddField(
            model_name='footer',
            name='column_2_text_2_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Column 2 > Text 2'),
        ),
        migrations.AddField(
            model_name='footer',
            name='column_2_text_3_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Column 2 > Text 3'),
        ),
        migrations.AddField(
            model_name='footer',
            name='column_2_text_3_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Column 2 > Text 3'),
        ),
        migrations.AddField(
            model_name='footer',
            name='column_2_title_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Column 2 > Title'),
        ),
        migrations.AddField(
            model_name='footer',
            name='column_2_title_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Column 2 > Title'),
        ),
        migrations.AddField(
            model_name='footer',
            name='column_3_text_1_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Column 3 > Text 1'),
        ),
        migrations.AddField(
            model_name='footer',
            name='column_3_text_1_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Column 3 > Text 1'),
        ),
        migrations.AddField(
            model_name='footer',
            name='column_3_text_2_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Column 3 > Text 2'),
        ),
        migrations.AddField(
            model_name='footer',
            name='column_3_text_2_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Column 3 > Text 2'),
        ),
        migrations.AddField(
            model_name='footer',
            name='column_3_text_3_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Column 3 > Text 3'),
        ),
        migrations.AddField(
            model_name='footer',
            name='column_3_text_3_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Column 3 > Text 3'),
        ),
        migrations.AddField(
            model_name='footer',
            name='column_3_title_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Column 3 > Title'),
        ),
        migrations.AddField(
            model_name='footer',
            name='column_3_title_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Column 3 > Title'),
        ),
        migrations.AddField(
            model_name='footer',
            name='column_4_text_1_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Column 4 > Text 1'),
        ),
        migrations.AddField(
            model_name='footer',
            name='column_4_text_1_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Column 4 > Text 1'),
        ),
        migrations.AddField(
            model_name='footer',
            name='column_4_title_de',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Column 4 > Title'),
        ),
        migrations.AddField(
            model_name='footer',
            name='column_4_title_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Column 4 > Title'),
        ),
    ]
