# Generated by Django 4.0.3 on 2022-05-25 15:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0066_applicant_employer_2_applicant_employer_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativeapplicationpage',
            name='header_text',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Header > Text'),
        ),
        migrations.AlterField(
            model_name='initiativeapplicationpage',
            name='header_text_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Header > Text'),
        ),
        migrations.AlterField(
            model_name='initiativeapplicationpage',
            name='header_text_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Header > Text'),
        ),
    ]
