# Generated by Django 4.0.3 on 2022-05-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0067_alter_initiativeapplicationpage_header_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='courses_text',
            field=models.TextField(blank=True, verbose_name='Courses > Text'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='courses_text_de',
            field=models.TextField(blank=True, null=True, verbose_name='Courses > Text'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='courses_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Courses > Text'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='courses_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Courses > Title'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='courses_title_de',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Courses > Title'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='courses_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Courses > Title'),
        ),
    ]
