# Generated by Django 4.0.3 on 2022-05-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0068_servicespage_courses_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='marital_status',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('DIVORCED', 'Divorced'), ('SEPERATED', 'Separated'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed')], max_length=20, verbose_name='Marital Status'),
        ),
    ]
