# Generated by Django 4.0.3 on 2022-06-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0069_alter_applicant_marital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='profession',
        ),
        migrations.AddField(
            model_name='applicant',
            name='country',
            field=models.CharField(default='', max_length=100, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='salutation',
            field=models.CharField(choices=[('M', 'Mr.'), ('F', 'Mrs.'), ('D', 'Diverse')], default='M', max_length=1, verbose_name='Salutation'),
            preserve_default=False,
        ),
    ]
