# Generated by Django 4.0.3 on 2022-06-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0072_alter_applicant_employer_alter_applicant_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='graduation_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Graduation End Date'),
        ),
    ]
