# Generated by Django 4.0.3 on 2022-06-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0073_alter_applicant_graduation_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='job_seeker_career',
            field=models.CharField(blank=True, max_length=200, verbose_name='Job Seeker > Career'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='job_seeker_career_de',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Job Seeker > Career'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='job_seeker_career_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Job Seeker > Career'),
        ),
    ]
