# Generated by Django 4.0.3 on 2022-06-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0074_navigation_job_seeker_career_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
