# Generated by Django 4.0.3 on 2022-09-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0078_indexpage_reviews_text_indexpage_reviews_text_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='customer',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
