# Generated by Django 4.0.3 on 2022-03-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name'], 'verbose_name': 'Nutzer', 'verbose_name_plural': 'Nutzer'},
        ),
    ]
