# Generated by Django 4.0.3 on 2022-03-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='applicants/applicant/photo/')),
                ('salutation', models.CharField(choices=[('M', 'Herr'), ('F', 'Frau'), ('D', 'Divers')], max_length=1)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('postal', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Ledig'), ('DIVORCED', 'Geschieden'), ('SEPERATED', 'Getrennt lebend'), ('MARRIED', 'Verheiratet'), ('WIDOWED', 'Verwitwet')], max_length=20)),
                ('language1', models.CharField(max_length=50)),
                ('language1knowledge', models.CharField(max_length=20)),
                ('language2', models.CharField(max_length=50)),
                ('language2knowledge', models.CharField(max_length=20)),
                ('language3', models.CharField(max_length=50)),
                ('language3knowledge', models.CharField(max_length=20)),
                ('language4', models.CharField(max_length=50)),
                ('language4knowledge', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=50)),
                ('employer', models.CharField(max_length=50)),
                ('from_date', models.DateField()),
                ('unitl_date', models.DateField()),
                ('cv', models.FileField(upload_to='applicants/applicant/cv/')),
                ('more', models.FileField(upload_to='applicants/applicant/more/')),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
            },
        ),
    ]
