# Generated by Django 4.0.3 on 2022-03-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='unitl_date',
            new_name='until_date',
        ),
    ]
