# Generated by Django 4.0.3 on 2022-03-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_rename_unitl_date_applicant_until_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=models.ImageField(upload_to='applicants/applicant/photo/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='salutation',
            field=models.CharField(choices=[('M', 'Herr'), ('F', 'Frau'), ('D', 'Divers')], max_length=1, verbose_name='Salutation'),
        ),
    ]
