# Generated by Django 4.0.3 on 2022-04-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0004_applicant_created_applicant_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='language2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='language2knowledge',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='language3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='language3knowledge',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='language4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='language4knowledge',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='more',
            field=models.FileField(blank=True, upload_to='applicants/applicant/more/'),
        ),
    ]
